linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - typecheck
    - revive
    - gosec
    - unconvert
    - goconst
    - misspell
    - prealloc

linters-settings:
  govet:
    check-shadowing: true
  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck
  goconst:
    min-len: 2
    min-occurrences: 3

run:
  deadline: 5m
  tests: true
  skip-dirs:
    - vendor/
    - go/


issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true 